version: 2

updates:
  - package-ecosystem: npm
    directory: "/"
    groups:
      eslint:
        patterns:
          - "@typescript-eslint/*"
          - "eslint*"
      jest:
        patterns:
          - "@types/jest"
          - "jest*"
          - "ts-jest"
      prettier:
        patterns:
          - "prettier*"
      typescript:
        patterns:
          - "typescript*"
      mcp:
        patterns:
          - "@modelcontextprotocol/*"
    schedule:
      interval: weekly

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
